mutation updateUserViews($challengeSectionUnitId: Int!, $isCompleted: Boolean) {
    updateUserViews(
      challengeSectionUnitId: $challengeSectionUnitId,
      isCompleted: $isCompleted
    ) {
      user {
        lessonsCompleted
      } 
    }
  }